# string functions
from pyscript import display, document

def generate_card(enter):
    name = document.getElementById('input1').value
    age = document.getElementById('input2').value
    school = document.getElementById('input3').value
    
    message = f"""Student Profile:\n
    Name: {name}\t
    Age: {age}\t
    School: {school}\t


Generated Message:\n
{name}\'s age is {age} years old and goes to {school}. This information is generated by Python & Pyscript.
"""

    display(message, target="output")





